import { beforeEach, describe, expect, it, vi } from "vitest"

// Capture every execFileSync invocation so we can assert that
// checkoutPrBranch discards working-tree state (git reset --hard, git clean)
// BEFORE invoking `gh pr checkout`. Without this, an uncommitted file from
// an earlier step (e.g. payload's importMap.js regenerated by pnpm install)
// makes gh refuse with "Your local changes would be overwritten by checkout"
// and crashes the entire executable.
const calls: { cmd: string; args: string[] }[] = []

vi.mock("node:child_process", async (orig) => {
  const actual = (await orig()) as typeof import("node:child_process")
  return {
    ...actual,
    execFileSync: vi.fn((cmd: string, args: string[], opts?: { encoding?: string }) => {
      calls.push({ cmd, args })
      // Honor encoding="utf-8" callers (getCurrentBranch). Buffer-mode
      // callers (gh pr checkout etc.) get an empty Buffer.
      if (cmd === "git" && args[0] === "rev-parse" && args[1] === "--abbrev-ref") {
        return opts?.encoding === "utf-8" ? "kody/test-branch\n" : Buffer.from("kody/test-branch\n")
      }
      return opts?.encoding === "utf-8" ? "" : Buffer.from("")
    }),
  }
})

describe("checkoutPrBranch: clears working-tree state before checkout", () => {
  beforeEach(() => {
    calls.length = 0
  })

  it("runs `git reset --hard HEAD` and `git clean -fd` before `gh pr checkout`", async () => {
    const { checkoutPrBranch } = await import("../../src/branch.js")
    checkoutPrBranch(1556, "/tmp/fake-repo")
    const order = calls.map((c) => `${c.cmd} ${c.args.join(" ")}`)
    const resetIdx = order.findIndex((s) => s === "git reset --hard HEAD")
    const cleanIdx = order.findIndex((s) => s === "git clean -fd")
    const checkoutIdx = order.findIndex((s) => s === "gh pr checkout 1556")
    expect(resetIdx).toBeGreaterThanOrEqual(0)
    expect(cleanIdx).toBeGreaterThanOrEqual(0)
    expect(checkoutIdx).toBeGreaterThanOrEqual(0)
    expect(resetIdx).toBeLessThan(checkoutIdx)
    expect(cleanIdx).toBeLessThan(checkoutIdx)
  })

  it("still attempts gh pr checkout when the cleanup commands fail (best-effort)", async () => {
    // If the cwd isn't a git repo yet, git reset/clean throw — but we
    // shouldn't bail because of that; the real signal is what gh pr
    // checkout returns.
    const { execFileSync } = await import("node:child_process")
    const mock = execFileSync as unknown as ReturnType<typeof vi.fn>
    mock.mockImplementationOnce((cmd: string, args: string[]) => {
      calls.push({ cmd, args })
      throw new Error("not a git repository")
    })
    // Subsequent calls succeed
    mock.mockImplementation((cmd: string, args: string[], opts?: { encoding?: string }) => {
      calls.push({ cmd, args })
      if (cmd === "git" && args[0] === "rev-parse") {
        return opts?.encoding === "utf-8" ? "kody/x\n" : Buffer.from("kody/x\n")
      }
      return opts?.encoding === "utf-8" ? "" : Buffer.from("")
    })
    const { checkoutPrBranch } = await import("../../src/branch.js")
    expect(() => checkoutPrBranch(99, "/tmp/fake")).not.toThrow()
    const checkoutCall = calls.find((c) => c.cmd === "gh" && c.args[0] === "pr" && c.args[1] === "checkout")
    expect(checkoutCall).toBeDefined()
  })
})
